use_frameworks!
platform :ios, '13.4'

target 'JVMenu_Example' do
  pod 'JVMenu', :path => '../'

  target 'JVMenu_Tests' do
    inherit! :search_paths
  end
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        end
    end
end
